### ISSUE TITLE
某麦小飞机群链接过期,麻烦大佬重新分享下

### ISSUE THREAD

**Issue by zjlhcnlay** [svcvit/Awesome-Dify-Workflow#5]
分享一个 tg 讨论组， https://t.me/+IbWm3n0o1KlkMTg1 ,感谢 @svcvit    过期了

**Comment by Jsra1n** [comment]
> 分享一个 tg 讨论组， https://t.me/+IbWm3n0o1KlkMTg1 ,感谢 @svcvit 过期了

找到新的了没？
