### ISSUE TITLE
Failed to get tool runtime: workflow provider 0ad29728-5209-4afe-bc96-daff03091c42 not found

### ISSUE THREAD

**Issue by wisepmlin** [svcvit/Awesome-Dify-Workflow#6]
Failed to get tool runtime: workflow provider 0ad29728-5209-4afe-bc96-daff03091c42 not found
<img width="459" alt="截屏2024-09-20 11 56 44" src="https://github.com/user-attachments/assets/23706fa1-c88f-4bd3-b99c-e7b827701392">
缺少这个节点工具，这个本地爬虫是插件吗？还是其他节点

**Comment by Astrcu** [comment]
解决了吗
